#!/bin/bash
# Auto-update agent roster after agent file changes
# Triggered by PostToolUse hook on Write/Edit to .claude/agents/*.md

PROJECT_DIR="/Users/robertrhu/Projects/story-portal"
AGENTS_DIR="$PROJECT_DIR/.claude/agents"
ROSTER_FILE="$AGENTS_DIR/ROSTER.md"
TIMESTAMP=$(date "+%B %d, %Y")

# Only run if an agent file was modified (not ROSTER.md itself)
MODIFIED_FILE="$1"
if [[ "$MODIFIED_FILE" == *"ROSTER.md"* ]]; then
  exit 0
fi

# Check if we're dealing with an agent file
if [[ ! "$MODIFIED_FILE" == *".claude/agents/"* ]]; then
  exit 0
fi

# Count agents (excluding ROSTER.md)
AGENT_COUNT=$(find "$AGENTS_DIR" -name "*.md" ! -name "ROSTER.md" | wc -l | tr -d ' ')

# Generate the roster header
cat > "$ROSTER_FILE" << EOF
# Agent Roster

**Project:** Story Portal
**Last Updated:** $TIMESTAMP
**Auto-generated:** Yes (via PostToolUse hook)

---

## Quick Stats

| Metric | Value |
|--------|-------|
| Total Agents | $AGENT_COUNT |
| Source | \`.claude/agents/*.md\` |

---

## Agents

EOF

# Parse each agent file and extract metadata
for agent_file in "$AGENTS_DIR"/*.md; do
  filename=$(basename "$agent_file")

  # Skip ROSTER.md
  if [[ "$filename" == "ROSTER.md" ]]; then
    continue
  fi

  # Extract agent name from first # heading
  agent_name=$(grep -m1 "^# " "$agent_file" | sed 's/^# //' | sed 's/ — .*//')

  # Extract department
  department=$(grep -m1 "^\*\*Department:\*\*" "$agent_file" | sed 's/.*\*\*Department:\*\* //')

  # Extract classification
  classification=$(grep -m1 "^\*\*Classification:\*\*" "$agent_file" | sed 's/.*\*\*Classification:\*\* //')

  # Default values if not found
  agent_name=${agent_name:-"Unknown"}
  department=${department:-"—"}
  classification=${classification:-"—"}

  cat >> "$ROSTER_FILE" << EOF
### $agent_name
- **File:** \`.claude/agents/$filename\`
- **Department:** $department
- **Classification:** $classification

EOF

done

# Add footer
cat >> "$ROSTER_FILE" << EOF
---

## Maintenance

This file is auto-generated by \`.claude/hooks/update-agent-roster.sh\`.

To add a new agent:
1. Create \`.claude/agents/[name].md\` with role template
2. Include frontmatter: Department, Classification
3. ROSTER.md updates automatically on next file save

To manually refresh:
\`\`\`bash
.claude/hooks/update-agent-roster.sh .claude/agents/any-file.md
\`\`\`

---

*Auto-generated on $TIMESTAMP*
EOF

echo "Updated: $ROSTER_FILE"
exit 0
