#!/bin/bash
# Auto-update agent roster and browser after .claude/ file changes
# Triggered by PostToolUse hook on Write/Edit to .claude/**/*.md

PROJECT_DIR="/Users/robertrhu/Projects/story-portal"
AGENTS_DIR="$PROJECT_DIR/.claude/agents"
ROSTER_FILE="$AGENTS_DIR/ROSTER.md"
BROWSER_GENERATOR="$PROJECT_DIR/.claude/tools/generate-agent-browser.mjs"
TIMESTAMP=$(date "+%B %d, %Y")

MODIFIED_FILE="$1"

# Skip if modifying ROSTER.md itself (prevent infinite loop)
if [[ "$MODIFIED_FILE" == *"ROSTER.md"* ]]; then
  exit 0
fi

# Check if we're dealing with a .claude/ file that should trigger updates
if [[ ! "$MODIFIED_FILE" == *".claude/"* ]]; then
  exit 0
fi

# Determine what was modified
IS_AGENT=false
IS_SKILL=false
IS_COMMAND=false

if [[ "$MODIFIED_FILE" == *".claude/agents/"* ]]; then
  IS_AGENT=true
fi
if [[ "$MODIFIED_FILE" == *".claude/skills/"* ]]; then
  IS_SKILL=true
fi
if [[ "$MODIFIED_FILE" == *".claude/commands/"* ]]; then
  IS_COMMAND=true
fi

# If not an agent, skill, or command, exit
if [[ "$IS_AGENT" == false && "$IS_SKILL" == false && "$IS_COMMAND" == false ]]; then
  exit 0
fi

# Regenerate agent browser (for any .claude/ content change)
if [[ -f "$BROWSER_GENERATOR" ]]; then
  node "$BROWSER_GENERATOR" 2>/dev/null
  echo "Regenerated: /tmp/agent-browser.html"
fi

# Only regenerate ROSTER.md if an agent file was modified
if [[ "$IS_AGENT" == false ]]; then
  exit 0
fi

# Count agents (excluding ROSTER.md)
AGENT_COUNT=$(find "$AGENTS_DIR" -name "*.md" ! -name "ROSTER.md" | wc -l | tr -d ' ')

# Generate the roster header
cat > "$ROSTER_FILE" << EOF
# Agent Roster

**Project:** Story Portal
**Last Updated:** $TIMESTAMP
**Auto-generated:** Yes (via PostToolUse hook)

---

## Quick Stats

| Metric | Value |
|--------|-------|
| Total Agents | $AGENT_COUNT |
| Source | \`.claude/agents/*.md\` |

---

## Agents

EOF

# Parse each agent file and extract metadata
for agent_file in "$AGENTS_DIR"/*.md; do
  filename=$(basename "$agent_file")

  # Skip ROSTER.md
  if [[ "$filename" == "ROSTER.md" ]]; then
    continue
  fi

  # Extract agent name from first # heading
  agent_name=$(grep -m1 "^# " "$agent_file" | sed 's/^# //' | sed 's/ — .*//')

  # Extract department
  department=$(grep -m1 "^\*\*Department:\*\*" "$agent_file" | sed 's/.*\*\*Department:\*\* //')

  # Extract classification
  classification=$(grep -m1 "^\*\*Classification:\*\*" "$agent_file" | sed 's/.*\*\*Classification:\*\* //')

  # Default values if not found
  agent_name=${agent_name:-"Unknown"}
  department=${department:-"—"}
  classification=${classification:-"—"}

  cat >> "$ROSTER_FILE" << EOF
### $agent_name
- **File:** \`.claude/agents/$filename\`
- **Department:** $department
- **Classification:** $classification

EOF

done

# Add footer
cat >> "$ROSTER_FILE" << EOF
---

## Maintenance

This file is auto-generated by \`.claude/hooks/update-agent-roster.sh\`.

To add a new agent:
1. Create \`.claude/agents/[name].md\` with role template
2. Include frontmatter: Department, Classification
3. ROSTER.md updates automatically on next file save

To manually refresh:
\`\`\`bash
.claude/hooks/update-agent-roster.sh .claude/agents/any-file.md
\`\`\`

---

*Auto-generated on $TIMESTAMP*
EOF

echo "Updated: $ROSTER_FILE"
exit 0
