#!/usr/bin/env node

import * as fs from 'fs'
import * as path from 'path'

const ASSETS_DIR = 'public/assets'
const OUTPUT_FILE = 'docs/ASSET_CATALOG.md'

function walkDir(dir, basePath = '') {
  const entries = []
  const items = fs.readdirSync(dir, { withFileTypes: true })

  for (const item of items) {
    if (item.name.startsWith('.')) continue

    const fullPath = path.join(dir, item.name)
    const relativePath = path.join(basePath, item.name)

    if (item.isDirectory()) {
      entries.push(...walkDir(fullPath, relativePath))
    } else {
      const stats = fs.statSync(fullPath)
      entries.push({
        path: `/assets/${relativePath}`,
        size: stats.size,
        modified: stats.mtime.toISOString(),
      })
    }
  }

  return entries
}

function formatSize(bytes) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function generateCatalog() {
  const entries = walkDir(ASSETS_DIR)

  const categories = {
    images: [],
    fonts: [],
    ui: [],
    audio: [],
    other: [],
  }

  for (const entry of entries) {
    if (entry.path.includes('/images/')) {
      categories.images.push(entry)
    } else if (entry.path.includes('/fonts/')) {
      categories.fonts.push(entry)
    } else if (entry.path.includes('/ui/')) {
      categories.ui.push(entry)
    } else if (entry.path.includes('/audio/')) {
      categories.audio.push(entry)
    } else {
      categories.other.push(entry)
    }
  }

  let markdown = `# Asset Catalog

> Auto-generated by \`pnpm assets:catalog\`. Do not edit manually.

Generated: ${new Date().toISOString()}

## Summary

| Category | Count |
|----------|-------|
| Images | ${categories.images.length} |
| Fonts | ${categories.fonts.length} |
| UI | ${categories.ui.length} |
| Audio | ${categories.audio.length} |
| Other | ${categories.other.length} |
| **Total** | **${entries.length}** |

`

  for (const [category, items] of Object.entries(categories)) {
    if (items.length === 0) continue

    markdown += `## ${category.charAt(0).toUpperCase() + category.slice(1)}\n\n`
    markdown += `| Path | Size | Modified |\n`
    markdown += `|------|------|----------|\n`

    for (const item of items.sort((a, b) => a.path.localeCompare(b.path))) {
      markdown += `| \`${item.path}\` | ${formatSize(item.size)} | ${item.modified.split('T')[0]} |\n`
    }

    markdown += '\n'
  }

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
  fs.writeFileSync(OUTPUT_FILE, markdown)

  console.log(`Asset catalog generated: ${OUTPUT_FILE}`)
  console.log(`Total assets: ${entries.length}`)
}

generateCatalog()
